package autocode

type ServiceGroup struct {
	// Code generated by github.com/liwss/kubernetesAdmin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	// Code generated by github.com/liwss/kubernetesAdmin/server End; DO NOT EDIT.
}
