package autocode

type RouterGroup struct {
	// Code generated by github.com/liwss/kubernetesAdmin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	// Code generated by github.com/liwss/kubernetesAdmin/server End; DO NOT EDIT.
}
