package autocode

type ApiGroup struct {
	// Code generated by github.com/liwss/kubernetesAdmin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	// Code generated by github.com/liwss/kubernetesAdmin/server End; DO NOT EDIT.
}
